[project]
name = "multiversum-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "multiversum>=0.2.0",
    "scikit-learn>=1.5.2",
]
